@isTest
private class OB_OperationInfoForReplacement_CC_Test {

    static testmethod void getFieldUserLoggedTest(){
        Test.startTest();
        OB_OperationInfoForReplacement_CC.getFieldValuesForPetitioner();
        Test.stopTest();
    }

    static testmethod void getFieldValuesForUnistallationProcedureTest(){
        Test.startTest();
        OB_OperationInfoForReplacement_CC.getFieldValuesForUnistallationProcedure();
        Test.stopTest();
    }

}